# Profile information
name: Shannon's Advice Blog
title: Shannon's Advice Blog
description:
  Making it as a software engineer can be overwhelming. Here are some posts I wrote to help people learn practical software skills and improve the job hunting experience.
permalink: ':title/'
url: https://shannonphu.github.io/advice

# Social
email: shannonphu@gmail.com

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
